version: '3.7'
services:
  db:
    container_name: db
    image: mongo
    env_file:
      - .env
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  db-express:
    container_name: db-express
    image: mongo-express
    depends_on:
      - db
    ports:
      - "8081:8081"
    restart: always
    env_file:
      - .env

  api:
    container_name: api
    build: ./api
    ports:
      - "8000:8000"
    links:
      - db
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  app:
    container_name: app
    build: ./app
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always
    links:
      - db
    depends_on:
      - api

  setup-music:
    container_name: setup-music
    build: ./setup-music
    volumes:
      - ./setup-music:/setup-music

volumes:
  db_data:
  db_config:
    
